import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/other/Nav";
import Footer from "@/components/other/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Resqdex Project</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      {/* Hydration Error is Suppressed in the body */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
        <Nav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
